### ISSUE TITLE
Task 2: Calculate Finger tables

### ISSUE THREAD

**Issue by burstrom** [burstrom/D7024E_2015#2]

**Comment by maxkoi** [comment]
We (Jimmie, Dennis, Victor, Johan and I) have sent an e-mail to the lab supervisor Johan with a picture about Chord fingertables for him to explain. The idea we have for calculating finger tables the following: If the solution is not in the first half of the node circle, we use the longest finger(k=3 in 3bit system) to send us to the other half, and then proceed to find the solution.
